name: Package Tests with conda environment

on:
  push

jobs:
  setup_env:
    name: Setup environment
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Create Environment and update files. 
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: vformer
          environment-file: environment.yml
          python-version: 3.7
          auto-activate-base: false
      - run: |
          conda info
          conda list
