name: Package Tests

on:
  push
jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7", "3.8"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda information
        shell: bash -l {0}
        run: conda info
      
      - name: Install Packages with environment.yml file
        shell: bash -l {0}
        run : |
        conda create -f environment.yml
        conda activate vformer
        cd vformer
        pytest
        
